import json
import re
import time
from pathlib import Path

from openai import OpenAI
from tenacity import retry, stop_after_attempt, wait_fixed

from app.core.config import settings
from app.core.logging import logger
from app.schemas.resume_dto import ResumeDTO
from pathlib import Path

class LLMService:

    _client = None
    _system_prompt = None

    def __init__(self):

        if LLMService._client is None:

            logger.info("Initializing Qwen Client...")

            LLMService._client = OpenAI(
                api_key=settings.LLM_API_KEY,
                base_url=settings.LLM_BASE_URL,
            )

            prompt_path = (
                Path(__file__)
                .parent.parent
                / "prompts"
                / "resume_prompt.txt"
            )

            with open(
                prompt_path,
                "r",
                encoding="utf-8",
            ) as f:

                LLMService._system_prompt = f.read()

        self.client = LLMService._client
        self.system_prompt = LLMService._system_prompt

    def clean_json(self, response: str) -> str:
        response = response.strip()

        # Remove markdown code fences
        response = re.sub(
            r"```json",
            "",
            response,
            flags=re.IGNORECASE,
        )

        response = re.sub(
            r"```",
            "",
            response,
        )

        # Remove Qwen thinking blocks
        response = re.sub(
            r"<think>.*?</think>",
            "",
            response,
            flags=re.DOTALL,
        )

        # Extract only JSON
        start = response.find("{")
        end = response.rfind("}")

        if start != -1 and end != -1:
            response = response[start:end + 1]

        return response.strip()

    # @retry(
    #     stop=stop_after_attempt(3),
    #     wait=wait_fixed(2),
    # )


    def call_llm(
    self,
    prompt_file: str,
    text: str,
) -> dict:
        """
        Generic LLM caller.
        """

        prompt_path = (
            Path(__file__).parent.parent
            / "prompts"
            / prompt_file
        )

        with open(
            prompt_path,
            "r",
            encoding="utf-8",
        ) as f:

            system_prompt = f.read()

        logger.info("Calling Qwen...")

        start = time.time()

        response = self.client.chat.completions.create(

            model=settings.LLM_MODEL,

            temperature=0,

            messages=[
                {
                    "role": "system",
                    "content": system_prompt,
                },
                {
                    "role": "user",
                    "content": text,
                },
            ],
        )

        elapsed = round(
            time.time() - start,
            2,
        )

        logger.info(
            f"Qwen finished in {elapsed} sec"
        )

        content = response.choices[0].message.content

        logger.info(
            "========== RAW QWEN RESPONSE =========="
        )
        logger.info(content)
        logger.info(
            "======================================"
        )

        content = self.clean_json(content)
        parsed = json.loads(content)

        if prompt_file == "resume_prompt.txt":
            parsed = self.normalize(parsed)

        return parsed


    def extract_resume(
        self,
        resume_text: str,
    ) -> ResumeDTO:
        parsed = self.call_llm(
        "resume_prompt.txt",
        resume_text,)

        return ResumeDTO(
            file_name="",
            file_hash="",
            raw_text="",
            **parsed,
        )

    def normalize(self, data: dict) -> dict:
        """
        Remove empty objects generated by the LLM.
        """
        def remove_empty(items):
            cleaned = []

            for item in items:

                if isinstance(item, dict):

                    has_data = False

                    for value in item.values():

                        if isinstance(value, list):
                            if any(str(v).strip() for v in value):
                                has_data = True
                                break

                        elif str(value).strip():
                            has_data = True
                            break

                    if has_data:
                        cleaned.append(item)

                elif isinstance(item, str):
                    if item.strip():
                        cleaned.append(item)

            return cleaned

        data["education"] = remove_empty(
            data.get("education", [])
        )

        data["experience"] = remove_empty(
            data.get("experience", [])
        )

        data["projects"] = remove_empty(
            data.get("projects", [])
        )

        data["certifications"] = remove_empty(
            data.get("certifications", [])
        )

        data["skills"] = [
            skill
            for skill in data.get("skills", [])
            if skill.strip()
        ]

        return data